In [1]:
# package
import numpy as np
from scipy import stats
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
# Problem Statement 1:
# In each of the following situations, state whether it is a correctly stated hypothesis
# testing problem and why?

# 1. H0: μ = 25, H1: μ ≠ 25
# this correctly stated hypothesis, because null & alternate hypothesis are correctly opposite

# 2. H0: σ > 10, H1: σ = 10
# this didn't correctly state hypothesis, because null & alternate hypothesis are not correctly opposite

# 3. H0: x = 50, H1: x ≠ 50
# this correctly stated hypothesis, because null & alternate hypothesis are correctly opposite
        
# 4. H0: p= 0.1, H1: p = 0.5
# this didn't correctly stated hypothesis, because null & alternate hypothesis are not correctly written, 
# alternate hypothesis should be H1 : p != 0.1

        
# 5. H0: s = 30, H1: s > 30
# this didn't correctly stated hypothesis, because altrnate hypothesis should be H1 : s!=30


In [3]:
# Problem Statement 2:
# The college bookstore tells prospective students that the average cost of its
# textbooks is Rs. 52 with a standard deviation of Rs. 4.50. A group of smart statistics
# students thinks that the average cost is higher. To test the bookstore’s claim against
# their alternative, the students will select a random sample of size 100. Assume that
# the mean from their random sample is Rs. 52.80. Perform a hypothesis test at the
# 5% level of significance and state your decision.

# solution
# H0 : mu = 52
# H1 : mu =! 52

# it is two tailed z test
# here we performing hypothesis testig via P value approach
# level of significance (alpha) = 0.05
z = (52.80-52)/(4.50/np.sqrt(100))
print("z value (data) =",z)
print("p value for z (data) =", (1-stats.norm.cdf(z))*2)
print("the p value of data is greater than significance level alpha (0.05)")
print("so we do not reject null hypothesis, conclusion is that the average cost of bookstore textbooks is Rs. 52 ")

z value (data) = 1.7777777777777715
p value for z (data) = 0.0754403596268014
the p value of data is greater than significance level alpha (0.05)
so we do not reject null hypothesis, conclusion is that the average cost of bookstore textbooks is Rs. 52 


In [4]:
# Problem Statement 3:
# A certain chemical pollutant in the Genesee River has been constant for several
# years with mean μ = 34 ppm (parts per million) and standard deviation σ = 8 ppm. A
# group of factory representatives whose companies discharge liquids into the river is
# now claiming that they have lowered the average with improved filtration devices. A
# group of environmentalists will test to see if this is true at the 1% level of
# significance. Assume \ that their sample of size 50 gives a mean of 32.5 ppm.
# Perform a hypothesis test at the 1% level of significance and state your decision.

# solution 
# H0 : mu < 34
# H1 : mu > 34

# it is right tailed z test
# here we are performing critical value approach
# level of significance alpha = 0.01

z = (32.5-34)/(8/np.sqrt(50))
print("z value for data =",z)
print("z value for alpha =", 1-stats.norm.ppf(0.01))
print("z value (data)< z value (alpha)")
print("so do not reject null hypothesis, so the claimed of group of factory representatives is correct")

z value for data = -1.3258252147247767
z value for alpha = 3.3263478740408408
z value (data)< z value (alpha)
so do not reject null hypothesis, so the claimed of group of factory representatives is correct


In [5]:
# Problem Statement 4:
# Based on population figures and other general information on the U.S. population,
# suppose it has been estimated that, on average, a family of four in the U.S. spends
# about $1135 annually on dental expenditures. Suppose further that a regional dental
# association wants to test to determine if this figure is accurate for their area of
# country. To test this, 22 families of 4 are randomly selected from the population in
# that area of the country and a log is kept of the family’s dental expenditure for one
# year. The resulting data are given below. Assuming, that dental expenditure is
# normally distributed in the population, use the data and an alpha of 0.05 to test the
# dental association’s hypothesis.
# 1008, 812, 1117, 1323, 1308, 1415, 831, 1021, 1287, 851, 930, 730, 699,
# 872, 913, 944, 954, 987, 1695, 995, 1003, 994

# solution


data = np.array([1008, 812, 1117, 1323, 1308, 1415, 831, 1021, 1287, 851, 930, 730, 699,
872, 913, 944, 954, 987, 1695, 995, 1003, 994])

s_mean =np.mean(data)
s_std = np.std(data)
n = 22
alpha = 0.05

print("mean of sample data =", s_mean)
print("standard deviation of data =", s_std)

# H0 : mu = 1135
# H1 : mu != 1135

# so it is two tailed  t test
# here we are using p value approach

t = (s_mean-1135)/(s_std/np.sqrt(22))
print("t value of data = ", t)
print("p value (data)", (stats.t.cdf(t,df=21))*2)
print("p value (data) = alpha(0.05), so we do not reject null hypothesis, so  the claim of US on dental expenditure is incorrect")

mean of sample data = 1031.3181818181818
standard deviation of data = 234.84799462314425
t value of data =  -2.070747228595759
p value (data) 0.05089829008918908
p value (data) = alpha(0.05), so we do not reject null hypothesis, so  the claim of US on dental expenditure is incorrect


In [6]:
# Problem Statement 5:
# In a report prepared by the Economic Research Department of a major bank the
# Department manager maintains that the average annual family income on Metropolis
# is $48,432. What do you conclude about the validity of the report if a random sample
# of 400 families shows and average income of $48,574 with a standard deviation of
# 2000?

# solution

# H0 : mu = 48432
# H1 : mu != 48432

# so it is two tailed  z test
# here we are using p value approach
# alpha = 0.05

z = (48574-48432)/(2000/np.sqrt(400))

print("z value data",z)

print("z value for alpha", 1-stats.norm.cdf(z))

print("here p value of data > p value of alpha , so the null hypothesis is correct")
print("the claim of Economic Research Department of a major bank is correct")

z value data 1.42
z value for alpha 0.07780384052654643
here p value of data > p value of alpha , so the null hypothesis is correct
the claim of Economic Research Department of a major bank is correct


In [7]:
# Problem Statement 6:
# Suppose that in past years the average price per square foot for warehouses in the
# United States has been $32.28. A national real estate investor wants to determine
# whether that figure has changed now. The investor hires a researcher who randomly
# samples 19 warehouses that are for sale across the United States and finds that the
# mean price per square foot is $31.67, with a standard deviation of $1.29. assume
# that the prices of warehouse footage are normally distributed in population. If the
# researcher uses a 5% level of significance, what statistical conclusion can be
# reached? What are the hypotheses?

# solution

# H0 : mu = 32.28
# H1 : mu != 32.28

# so it is two tailed  t test
# here we are using t value approach
# alpha = 0.05

t = (31.67-32.28)/(1.29/np.sqrt(19))

print("t value data",t)

print("t value for alpha = ", stats.t.ppf(0.025,df=18))

print("here t value of data < t value of alpha in negative region & t value of data > t value of alpha in positive region , so the null hypothesis is correct")
print(" the claim of the average price per square foot for warehouses in the United States is correct")

t value data -2.06118477175179
t value for alpha =  -2.10092204024096
here t value of data < t value of alpha in negative region & t value of data > t value of alpha in positive region , so the null hypothesis is correct
 the claim of the average price per square foot for warehouses in the United States is correct


In [8]:
# Problem Statement 7:
# Fill in the blank spaces in the table and draw your conclusions from it.
# take standard daviation = 2.5


df = pd.DataFrame({"Acceptance region":['48.5<x<51.5','48<x<52','48.81<x<51.90','48.42<x<51.58'],"samle size":[10,10,16,16],"alpha":[0,0,0,0],"beta at mu = 52":[0,0,0,0],"beta at mu = 50.5":[0,0,0,0]})
df

Acceptance region  samle size  alpha  beta at mu = 52  beta at mu = 50.5
0       48.5<x<51.5          10      0                0                  0
1           48<x<52          10      0                0                  0
2     48.81<x<51.90          16      0                0                  0
3     48.42<x<51.58          16      0                0                  0

In [9]:
#calculating alpha column
#  mu = 50
def alpha(x,mu,sigma,n):
    z = (x-mu)/(sigma/np.sqrt(n))
    if z<0:
        alpha = stats.norm.cdf(z)
    else:
        alpha = 1-stats.norm.cdf(z)
    print(alpha)
    

    
a = alpha(48.5,50,2.5,10)
b = alpha(51.5,50,2.5,10)
c = 0.028889785561798602+0.028889785561798553
df.iloc[0,2]= c

a = alpha(48,50,2.5,10)
b = alpha(52,50,2.5,10)
c = 0.005706018193000826+0.005706018193000872
df.iloc[1,2]= c

a = alpha(48.81,50,2.5,16)
b = alpha(51.90,50,2.5,16)
c = 0.028455092091357957+0.0011828907431044033
df.iloc[2,2]= c

a = alpha(48.42,50,2.5,16)
b = alpha(51.58,50,2.5,16)
c = 0.005735717598536083+0.005735717598536077
df.iloc[3,2]= c

#calculating beta at mu = 52 column
# here mu1(50)<mu2(52), so will take only upper value in interval of probability
def beta(x,mu,sigma,n):
    z = (x-mu)/(sigma/np.sqrt(n))
    print(stats.norm.cdf(z))
    
beta_1 = beta(51.5,52,2.5,10)
df.iloc[0,3] = 0.26354462843276905

beta_2 = beta(52,52,2.5,10)
df.iloc[1,3] = 0.5

beta_3 = beta(51.90,52,2.5,16)
df.iloc[2,3] = 0.4364405371085663

beta_4 = beta(51.58,52,2.5,16)
df.iloc[3,3] = 0.2507918481599688

# beta at mu = 50.5

beta_value_1 = beta(51.50,50.5,2.5,10)
df.iloc[0,4] = 0.8970483946339658

beta_value_2 = beta(52,50.5,2.5,10)
df.iloc[1,4] = 0.9711102144382014

beta_value_3 = beta(51.90,50.5,2.5,16)
df.iloc[2,4] = 0.9874545385640534

beta_value_4 = beta(51.58,50.5,2.5,16)
df.iloc[3,4] = 0.9580058878111785


print('conclusions from it')
print('1.  As the interval will increse the value of alpha decreses but value of beta increses')
print('2.  as the no of sample size increses both error will decreses')

df

0.028889785561798602
0.028889785561798553
0.005706018193000826
0.005706018193000872
0.028455092091357957
0.0011828907431044033
0.005735717598536077
0.005735717598536083
0.26354462843276905
0.5
0.4364405371085663
0.2507918481599688
0.8970483946339658
0.9711102144382014
0.9874545385640534
0.9580058878111785
conclusions from it
1.  As the interval will increse the value of alpha decreses but value of beta increses
2.  as the no of sample size increses both error will decreses


Acceptance region  samle size     alpha  beta at mu = 52  beta at mu = 50.5
0       48.5<x<51.5          10  0.057780         0.263545           0.897048
1           48<x<52          10  0.011412         0.500000           0.971110
2     48.81<x<51.90          16  0.029638         0.436441           0.987455
3     48.42<x<51.58          16  0.011471         0.250792           0.958006

In [10]:
# Problem Statement 8:
# Find the t-score for a sample size of 16 taken from a population with mean 10 when
# the sample mean is 12 and the sample standard deviation is 1.5

def t_val(x,mu,sigma,n):
    t = (x-mu)/(sigma/np.sqrt(n))
    return t

a = t_val(12,10,1.5,16)
print('t value = ',a)

t value =  5.333333333333333


In [11]:
# Problem Statement 9:
# Find the t-score below which we can expect 99% of sample means will fall if samples
# of size 16 are taken from a normally distributed population.

b = stats.t.ppf(0.99,df=15)
print('the t-score below which we can expect 99% of sample means will fall =',b)

the t-score below which we can expect 99% of sample means will fall = 2.602480294995493


In [12]:
# Problem Statement 10:
# If a random sample of size 25 drawn from a normal population gives a mean of 60
# and a standard deviation of 4, find the range of t-scores where we can expect to find
# the middle 95% of all sample means. Compute the probability that (−t0.05 <t<t0.10).

t = stats.t.ppf(0.95,df=24)
print('t score =',t)

print('the probability that (−t0.05 <t<t0.10)= ', stats.t.cdf(0.10,df=24)-stats.t.cdf(-0.05,df=24))


t score = 1.7108820799094275
the probability that (−t0.05 <t<t0.10)=  0.05914441613731247


In [13]:
# Problem Statement 11:
# Two-tailed test for difference between two population means
# Is there evidence to conclude that the number of people travelling from Bangalore to
# Chennai is different from the number of people travelling from Bangalore to Hosur in
# a week, given the following:
# Population 1: Bangalore to Chennai n1 = 1200
# x1 = 452
# s1 = 212
# Population 2: Bangalore to Hosur n2 = 800
# x2 = 523
# s2 = 185

# solution

# H0 : mu1 = mu2
# H1 : mu1 != mu2

#  alpha = 0.05

def zvalue(x1_mean,x2_mean,s1,s2,n1,n2):
    z = ((x1_mean-x2_mean)/(np.sqrt(((np.square(s1))/n1)+((np.square(s2))/n2))))
    return z


a = zvalue(452,523,212,185,1200,800)
print("z value data =",a)

print("p value for data =",  stats.norm.cdf(a)*2)
print(" Here p value of  data < p value of alpha (0.05)")
print("so we will reject null hypothesis, It means both the populations are not same.")

z value data = -7.926428526759299
p value for data = 2.2553835335706493e-15
 Here p value of  data < p value of alpha (0.05)
so we will reject null hypothesis, It means both the populations are not same.


In [14]:
# Problem Statement 12:
# Is there evidence to conclude that the number of people preferring Duracell battery is
# different from the number of people preferring Energizer battery, given the following:
# Population 1: Duracell
# n1 = 100
# x1 = 308
# s1 = 84
# Population 2: Energizer
# n2 = 100
# x2 = 254
# s2 = 67

# solution

# H0 : mu1 = mu2
# H1 : mu1 != mu2

#  alpha = 0.05

a = zvalue(308,254,84,67,100,100)
print("z value of data",a)

print("p value of data", (1-stats.norm.cdf(a))*2)

print(" Here p value of  data < p value of alpha (0.05)")
print("so we will reject null hypothesis, It means both the populations are not same.")

z value of data 5.025702668336442
p value of data 5.015925257367826e-07
 Here p value of  data < p value of alpha (0.05)
so we will reject null hypothesis, It means both the populations are not same.


In [15]:
# Problem Statement 13:
# Pooled estimate of the population variance
# Does the data provide sufficient evidence to conclude that average percentage
# increase in the price of sugar differs when it is sold at two different prices?
# Population 1: Price of sugar = Rs. 27.50 n1 = 14
# x1 = 0.317%
# s1 = 0.12%
# Population 2: Price of sugar = Rs. 20.00 n2 = 9
# x2 = 0.21%
# s2 = 0.11%


# solution
# convert into values from percentages
# mu1 = 27.50
# mu2 = 20.00
# x1 = 36.21
# x2 =  24.2
# s1 = 4.34
# s2 = 2.66
# Degree of freedom = n1 + n2 -2 = 21
# H0 : mu1 = mu2
# H1 : mu1 != mu2

def tvalue(x1_mean,x2_mean,s1,s2,n1,n2):
    t = ((x1_mean-x2_mean)/(np.sqrt(((np.square(s1))/n1)+((np.square(s2))/n2))))
    return t



t = tvalue(36.21,24.20,4.34,2.66,14,9)
print("t value of data =",t)

print("p value of data =", (1-stats.t.cdf(t,df=21))*2)
print("here p value of data < p value of alpha (0.05)")
print("so we will reject null hypothesis")

t value of data = 8.226070276327205
p value of data = 5.2529272931423066e-08
here p value of data < p value of alpha (0.05)
so we will reject null hypothesis


In [16]:
# Problem Statement 14:
# The manufacturers of compact disk players want to test whether a small price
# reduction is enough to increase sales of their product. Is there evidence that the
# small price reduction is enough to increase sales of compact disk players?
# Population 1: Before reduction
# n1 = 15
# x1 = Rs. 6598 s1 = Rs. 844
# Population 2: After reduction n2 = 12
# x2 = RS. 6870
# s2 = Rs. 669

# solution
# Degree of freedom = n1 + n2 -2 = 25
# H0 : mu1 != mu2  (after price reduction sales are not same )
# H1 : mu1 == mu2  (sales are same)
# alpha = 0.05

t = tvalue(6598,6870,844,669,15,12)
print("t value of data =",t)

print("p value of data =", (stats.t.cdf(t,df=25))*2)
print('p value of data > alpha, so do not reject null hypothesis')
print('there is statistical evidence that a small price reduction is enough to increase sales of their product')

t value of data = -0.9341299576730813
p value of data = 0.3591723244639674
p value of data > alpha, so do not reject null hypothesis
there is statistical evidence that a small price reduction is enough to increase sales of their product


In [17]:
# Problem Statement 15:
# Comparisons of two population proportions when the hypothesized difference is zero
# Carry out a two-tailed test of the equality of banks’ share of the car loan market in
# 1980 and 1995.
# Population 1: 1980
# n1 = 1000
# x1 = 53
# p 1 = 0.53
# Population 2: 1985
# n2 = 100
# x2 = 43
# p 2= 0.53

# solution
# it is two sample proportion test

# H0 : p1 = p2
# H1 : p1 != p2

# alpha = 0.05

def pooled_pro(p1,p2,n1,n2):
    p = (p1*n1 + p2*n2)/ (n1+n2)
    return p

def standard_error(p,n1,n2):
    se = np.sqrt((p*(1-p))/(n1+n2))
    return se
    
def z_val(p1,p2,se):
    z = (p1-p2)/se
    return z


p = pooled_pro(0.53,0.53,1000,100)
print("pooled proportion for calculation of SE =",p)

SE = standard_error(p,1000,100)
print("standard error =", SE)

z = z_val(0.53,0.53,SE)
print("z value of data = ",z)

print("p value for data =", stats.norm.cdf(z))
print('p value of data >> alpha ')
print('so will fail to reject null hypothesis, it means the equality of banks’ share of the car loan market is equal')

pooled proportion for calculation of SE = 0.53
standard error = 0.015048406741397756
z value of data =  0.0
p value for data = 0.5
p value of data >> alpha 
so will fail to reject null hypothesis, it means the equality of banks’ share of the car loan market is equal


In [18]:
# Problem Statement 16:
# Carry out a one-tailed test to determine whether the population proportion of
# traveler’s check buyers who buy at least $2500 in checks when sweepstakes prizes
# are offered as at least 10% higher than the proportion of such buyers when no
# sweepstakes are on.
# Population 1: With sweepstakes
# n1 = 300
# x1 = 120
# p = 0.40
# Population 2: No sweepstakes n2 = 700
# x2 = 140
# p 2= 0.20

# solution
# H0 : p1 >= p2
# H1 : p1 < p2

p = pooled_pro(0.40,0.20,300,700)
print("pooled proportion for calculate SE =",p)

SE = standard_error(p,300,700)
print("standard error =", SE)

z = z_val(0.40,0.20,SE)
print("z value o data =", z)

print("p value of data =", (1-stats.norm.cdf(z)))
print("p value of data << alpha , so we reject null hypothesis")
print('p1 > p2 statment is true')

pooled proportion for calculate SE = 0.26
standard error = 0.013870832707519763
z value o data = 14.41874501821181
p value of data = 0.0
p value of data << alpha , so we reject null hypothesis
p1 > p2 statment is true


In [19]:
# Problem Statement 17:
# A die is thrown 132 times with the following results: Number turned up: 1, 2, 3, 4, 5, 6
# Frequency: 16, 20, 25, 14, 29, 28
# Is the die unbiased? Consider the degrees of freedom as p − 1

# solution

x = [1,2,3,4,5,6]
f = [16,20,25,14,29,28]
# expected = 132 * (1/6)= 22
E = [22,22,22,22,22,22]

# DF = 6-1
# chi_square = (observed - expected)^2/expected
# alpha = 0.05

# H0 : die is unbiased
# H1 : die is biased

lst = []

for i,j in zip(f,E):
    chi2 = np.square((i-j))/j
    lst.append(chi2)

a = np.sum(lst)
print("chi2 calculated value", a )

p_value= 1-stats.chi2.cdf(a,df=5)

print('p value =', p_value )
print('p value of data > alpha , so the do not reject null hypothesis')
print('die is unbiased')

chi2 calculated value 9.0
p value = 0.10906415794977253
p value of data > alpha , so the do not reject null hypothesis
die is unbiased


In [20]:
# Problem Statement 18:
# In a certain town, there are about one million eligible voters. A simple random
# sample of 10,000 eligible voters was chosen to study the relationship between
# gender and participation in the last election. The results are summarized in the
# following 2X2 (read two by two) contingency table:


# solution
# H0 : gender and voting are independent
# h1 : gender and voting are not independent

# alpha = 0.05

df = pd.DataFrame({'voting': ['VOTED','VOTED','NON VOTED','NON VOTED'],'gender': ['MEN','WOMEN','MEN','WOMEN'],'VALUES': [2792,3591,1486,2131]})


observed_frequency = pd.pivot_table(df,index='voting',columns='gender',values='VALUES')
print(observed_frequency)


chi2 , p_value , df , expected_frequency = stats.chi2_contingency(observed_frequency)

print("chi2 value =", chi2)

print("p_value =", p_value)

print("df =", df)


print("HERE p value of calculated chi2 < p value of alpha (0.05)")

print("so reject null hypothesis, concluded that the voting & gender not independent ")

expected_frequency

gender      MEN  WOMEN
voting                
NON VOTED  1486   2131
VOTED      2792   3591
chi2 value = 6.552337973968181
p_value = 0.01047464310091866
df = 1
HERE p value of calculated chi2 < p value of alpha (0.05)
so reject null hypothesis, concluded that the voting & gender not independent 


array([[1547.3526, 2069.6474],
       [2730.6474, 3652.3526]])

In [21]:
# Problem Statement 19:
# A sample of 100 voters are asked which of four candidates they would vote for in an
# election. The number supporting each candidate is given below:
df = pd.DataFrame({'HIGGINS':[41],'REARDON':[19],'WHITE':[24],'CARLTON':[16]})
print(df)

# solution

# H0 : all candidates are equal popular
# H1 : all candidates are not equal popular

# alpha = 0.05

# expected_frequency = (1/4)*100 = 0.25

observed_frequency = [41,19,24,16]
expected_frequency = [25,25,25,25]


lst = []
for i,j in zip(observed_frequency,expected_frequency):
    chi2 = np.square((i-j))/j
    lst.append(a)
    
    
chi2 = np.sum(lst)
print('chi2 calculated value =', chi2)

print("p value of calculated chi2 =", 1-stats.chi2.cdf(chi2,df=3))

print("p value of calculated chi2 < alpha value (0.05), so reject null hypothesis")
print("CONCLUSION : all candidates are not equal popular")

   HIGGINS  REARDON  WHITE  CARLTON
0       41       19     24       16
chi2 calculated value = 36.0
p value of calculated chi2 = 7.488376951858555e-08
p value of calculated chi2 < alpha value (0.05), so reject null hypothesis
CONCLUSION : all candidates are not equal popular


In [22]:
# Problem Statement 20:
# Children of three ages are asked to indicate their preference for three photographs of
# adults. Do the data suggest that there is a significant relationship between age and
# photograph preference? What is wrong with this study? [Chi-Square = 29.6, with 4
# df: p < 0.05]


# solution

# H0 : age and photograph preference are independent
#  H1 : age and photograph preference are  not independent

# alpha = 0.05

df = pd.DataFrame({'AGE_OF_CHILD':["5-6 YEARS","5-6 YEARS","5-6 YEARS","7-8 YEARS","7-8 YEARS","7-8 YEARS","9-10 YEARS","9-10 YEARS","9-10 YEARS"],'PHOTOGRAPH': ['A','B','C','A','B','C','A','B','C'],'values':[18,22,20,2,28,40,20,10,40]})
df

observed_values = pd.pivot_table(df,index='AGE_OF_CHILD',columns='PHOTOGRAPH',values='values')

chi2,p_value , DF , expected_values = stats.chi2_contingency(observed_values)

print('chi2 calculated values =',chi2)

print('p value of calculated chi2 =',p_value)

print('Degree of freedom =',DF)

print('expected values =', expected_values)
print('CONCLUSION : age and photograph preference are  not independent')

chi2 calculated values = 29.603174603174608
p value of calculated chi2 = 5.894582174262606e-06
Degree of freedom = 4
expected values = [[12. 18. 30.]
 [14. 21. 35.]
 [14. 21. 35.]]
CONCLUSION : age and photograph preference are  not independent


In [23]:
# Problem Statement 21:

# A study of conformity using the Asch paradigm involved two conditions: one where
# one confederate supported the true judgement and another where no confederate
# gave the correct response.


df = pd.DataFrame({'CONFIRMATION':['confirm','confirm','not confirm', 'not confirm'],'support_system':['support','no support','support','no support'],'value':[18,40,32,10]})


observed_frequency = pd.pivot_table(df,index='CONFIRMATION',columns='support_system',values='value')

observed_frequency

# solution

# H0 : confirmation and support  are independent
#  H1 : confirmation and support  are not independent

# alpha = 0.05

chi2 , p_value , DF , expected_frequency = stats.chi2_contingency(observed_frequency)


print('chi2 calculated values =',chi2)

print('p value of calculated chi2 =',p_value)

print('Degree of freedom =',DF)

print('expected values =', expected_values)

print('p value of calculated chi2 < alpha (0.05) , so reject null hypothesis')

print('CONCLUSION  : confirmation and support  are not independent')

chi2 calculated values = 18.10344827586207
p value of calculated chi2 = 2.092221924065813e-05
Degree of freedom = 1
expected values = [[12. 18. 30.]
 [14. 21. 35.]
 [14. 21. 35.]]
p value of calculated chi2 < alpha (0.05) , so reject null hypothesis
CONCLUSION  : confirmation and support  are not independent


In [24]:
# Problem Statement 22:
# We want to test whether short people differ with respect to their leadership qualities
# (Genghis Khan, Adolf Hitler and Napoleon were all stature-deprived, and how many midget
# MP's are there?) The following table shows the frequencies with which 43 short people and
# 52 tall people were categorized as "leaders", "followers" or as "unclassifiable". Is there a
# relationship between height and leadership qualities?


df = pd.DataFrame({'leadership_qualities':['leader','leader','follower','follower','unclassifiable','unclassifiable'],'height':['short','tall','short','tall','short','tall'],'value':[12,32,22,14,9,6]})

observed_frequency = pd.pivot_table(df,index='leadership_qualities',columns='height',values='value')
observed_frequency


# solution

# H0 : leadership_qualities and height are independent
#  H1 : leadership_qualities and height are  not independent

# alpha = 0.01

chi2 , p_value , DF , expected_frequency = stats.chi2_contingency(observed_frequency)

print('chi2 calculated values =',chi2)

print('p value of calculated chi2 =',p_value)

print('Degree of freedom =',DF)

print('expected values =', expected_values)

print('p value of calculated chi2 < alpha (0.01) , so reject null hypothesis')

print('CONCLUSION :  leadership_qualities and height are  not independent')

chi2 calculated values = 10.712198008709638
p value of calculated chi2 = 0.004719280137040844
Degree of freedom = 2
expected values = [[12. 18. 30.]
 [14. 21. 35.]
 [14. 21. 35.]]
p value of calculated chi2 < alpha (0.01) , so reject null hypothesis
CONCLUSION :  leadership_qualities and height are  not independent


In [25]:
# Problem Statement 23:

# Each respondent in the Current Population Survey of March 1993 was classified as
# employed, unemployed, or outside the labor force. The results for men in California age 35-
# 44 can be cross-tabulated by marital status, as follows:

df = pd.DataFrame({'employment_type':['employed','employed','employed','unemployed','unemployed','unemployed','not in labor force','not in labor force','not in labor force'],'marital_status':['married','seperated','never married','married','seperated','never married','married','seperated','never married'],'value':[679,103,114,63,10,20,42,18,25]})


observed_frequency = pd.pivot_table(df,index='employment_type',columns='marital_status',values='value')
observed_frequency

# solution

# H0 : employment_type and marital_status are independent
#  H1 : employment_type and marital_status are  not independent

# alpha = 0.01

chi2 , p_value , DF , expected_frequency = stats.chi2_contingency(observed_frequency)

print('chi2 calculated values =',chi2)

print('p value of calculated chi2 =',p_value)

print('Degree of freedom =',DF)

print('expected values =', expected_values)

print('p value of calculated chi2 < alpha (0.01) , so reject null hypothesis')

print('CONCLUSION :   employment_type and marital_status are  not independent.')

chi2 calculated values = 31.61310319407798
p value of calculated chi2 = 2.2949883042859918e-06
Degree of freedom = 4
expected values = [[12. 18. 30.]
 [14. 21. 35.]
 [14. 21. 35.]]
p value of calculated chi2 < alpha (0.01) , so reject null hypothesis
CONCLUSION :   employment_type and marital_status are  not independent.
